name: Unit tests

on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
